### ISSUE TITLE
Update README.md with a quick tutorial on how to update the website

### ISSUE THREAD

**Issue by duncanruiz** [mir-pucrs/mir-pucrs.github.io#2]
How can we edit the page??? 
I'd like do edit some of the components in pages.
Cheers,

**Comment by meneguzzi** [comment]
I will try to edit [README.md](../README.md) with a quick guide.

**Comment by meneguzzi** [comment]
But this will not happen this week.

**Comment by meneguzzi** [comment]
@duncanruiz I now put a mini tutorial on how to update your bibliography for publication in the website by changing [docs/publications.bib](https://github.com/mir-pucrs/mir-pucrs.github.io/blob/master/docs/publications.bib).
Instructions are at the [README.md](https://github.com/mir-pucrs/mir-pucrs.github.io/blob/master/README.md).

**Comment by meneguzzi** [comment]
Should have closed this a while ago.
