### ISSUE TITLE
Add a dynamic bibliography generator to website

### ISSUE THREAD

**Issue by meneguzzi** [mir-pucrs/mir-pucrs.github.io#8]
Amory suggested this website: http://bibbase.org/

Examples: 

- http://www.cs.toronto.edu/~fritz/
- http://sentilab.sabanciuniv.edu/publications/
- http://www.cogrob.org/publications/
- http://sdg.csail.mit.edu/publications.php

This should probably be done after partitioning the website

**Comment by holissoncunha** [comment]
The issue was solved.

**Comment by meneguzzi** [comment]
You should probably add instructions on how to generate the bibliography section.

**Comment by holissoncunha** [comment]
Write or paste one bibtex citation in the file publications.bib (docs/publications.bib).
More informations: http://bibbase.org/help
